runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'EavNNHM01lhaHGCb'
  INSTANCE_CONNECTION_NAME: 'vms-demo-project:us-central1:vms-database'

beta_settings:
  cloud_sql_instances: 'vms-demo-project:us-central1:vms-database'
